server:
  tomcat:
    uri-encoding: ISO-8859-1
  port: 8081
  
spring:
   datasource:
    url: jdbc:mysql://10.42.1.2:3306/solarman3_device?useLegacyDatetimeCode=false&characterEncoding=utf8
    username: dev
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      test-on-borrow: true
   aop:
#     proxy-target-class: true
     auto: false
logging:
  level:
    root: info

xxq:
  name: xiaxiuqiang
  age: 25
  sex: false

